# You must set the environment variable GPU
# export GPU=H100 | B200

SRC := all_reduce_educational.cu
OUT := all_reduce_educational.out
CMD := ./all_reduce_educational.out
CONFIG := standalone
include ../../common.mk
