GPU := B200
SRC := fp8_cublas_lt_gemm.cu
OUT := fp8_cublas_lt_gemm.out
CMD := ./fp8_cublas_lt_gemm.out
CONFIG := standalone
NVCCFLAGS := -lcublas -lcublasLt -fopenmp -lgomp
include ../../../common.mk
