GPU := B200
SRC := mxfp8_cublas_lt_gemm.cu
OUT := mxfp8_cublas_lt_gemm.out
CMD := ./mxfp8_cublas_lt_gemm.out
CONFIG := standalone
NVCCFLAGS := -lcublas -lcublasLt -fopenmp -lgomp
include ../../../common.mk
