# Example usage:
#   GPU := H100 | B200
#   SRC := kernel.cu
#   OUT := kernel
#   CMD := ./kernel
#   CONFIG := standalone | python | pytorch
#   include common.mk

# These should be set by the including Makefile
GPU ?= NOT_SET # H100 | B200
SRC ?= NOT_SET # ex. my_kernel.cu
OUT ?= NOT_SET # ex. _C$(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")
CMD ?= NOT_SET # ex. ./my_kernel, OMP_NUM_THREADS=1 torchrun --nproc_per_node=8 benchmark.py
CONFIG ?= NOT_SET # standalone | python | pytorch
ifeq ($(GPU),NOT_SET)
$(error GPU is not set. Please set GPU to B200 or H100)
endif
ifeq ($(SRC),NOT_SET)
$(error SRC is not set. Please set SRC to the entry .cu file)
endif
ifeq ($(OUT),NOT_SET)
$(error OUT is not set. Please set OUT to the target binary filename)
endif
ifeq ($(CMD),NOT_SET)
$(error CMD is not set. Please set CMD to run command)
endif
ifeq ($(CONFIG),NOT_SET)
$(error CONFIG is not set. Please set CONFIG to standalone, python, or pytorch)
endif

# Compiler configuration
NVCC := nvcc

# ThunderKittens configuration
THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
COMMON_DIR := $(dir $(THIS_MAKEFILE))
THUNDERKITTENS_ROOT := $(abspath $(COMMON_DIR)/..)

# Common flags
NVCCFLAGS += -std=c++20 -O3 --use_fast_math # VERY important to include this flag
NVCCFLAGS += -lrt -lpthread -ldl -lcuda -lcudadevrt -lcudart_static
NVCCFLAGS += --expt-extended-lambda --expt-relaxed-constexpr 
NVCCFLAGS += -forward-unknown-to-host-compiler 
NVCCFLAGS += -Xcompiler=-Wno-psabi -Xcompiler=-fno-strict-aliasing 
NVCCFLAGS += -Xnvlink=--verbose -Xptxas=--verbose -Xptxas=--warn-on-spills 
NVCCFLAGS += -I${THUNDERKITTENS_ROOT}/include -I${THUNDERKITTENS_ROOT}/prototype

# Development flags
NVCCFLAGS += -DNDEBUG # disable debug blocks
NVCCFLAGS += -lineinfo # show line number with compute-sanitizer (does not affect perf, but binary gets larger)
NVCCFLAGS += -ftemplate-backtrace-limit=0 # show full template trace

# Python configuration (i.e., run with Python + PyTorch, but C++-side does not use the PyTorch API)
ifeq ($(CONFIG),python)
PYTHON_VERSION ?= $(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('LDVERSION'))")
PYTHON_INCLUDES ?= $(shell python3 -c "import sysconfig; print('-I', sysconfig.get_path('include'), sep='')")
PYTHON_LIBDIR ?= $(shell python3 -c "import sysconfig; print('-L', sysconfig.get_config_var('LIBDIR'), sep='')")
PYBIND_INCLUDES ?= $(shell python3 -m pybind11 --includes)
NVCCFLAGS += -shared -fPIC # make shared object
NVCCFLAGS += -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__
NVCCFLAGS += -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__
NVCCFLAGS += $(PYTHON_INCLUDES) ${PYTHON_LIBDIR} $(PYBIND_INCLUDES)
NVCCFLAGS += -lpython${PYTHON_VERSION} 
endif

# PyTorch configuration (i.e., run with Python + PyTorch, and C++-side uses the PyTorch API)
ifeq ($(CONFIG),pytorch)
PYTHON_VERSION ?= $(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('LDVERSION'))")
PYTHON_INCLUDES ?= $(shell python3 -c "import sysconfig; print('-I', sysconfig.get_path('include'), sep='')")
PYTHON_LIBDIR ?= $(shell python3 -c "import sysconfig; print('-L', sysconfig.get_config_var('LIBDIR'), sep='')")
PYBIND_INCLUDES ?= $(shell python3 -m pybind11 --includes)
PYTORCH_INCLUDES ?= $(shell python3 -c "from torch.utils.cpp_extension import include_paths; print(' '.join(['-I' + p for p in include_paths()]))") # recommended: define as an environment variable in advance
PYTORCH_LIBDIR ?= $(shell python3 -c "from torch.utils.cpp_extension import library_paths; print(' '.join(['-L' + p for p in library_paths()]))") # recommended: define as an environment variable in advance
NVCCFLAGS += -shared -fPIC # make shared object
NVCCFLAGS += -diag-suppress 3189 # for warnings generated by PyTorch C++ headers
NVCCFLAGS += -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__
NVCCFLAGS += -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__
NVCCFLAGS += -DTORCH_API_INCLUDE_EXTENSION_H
NVCCFLAGS += -DTORCH_EXTENSION_NAME=_C
NVCCFLAGS += $(PYTHON_INCLUDES) ${PYTHON_LIBDIR} $(PYBIND_INCLUDES)
NVCCFLAGS += ${PYTORCH_LIBDIR} $(PYTORCH_INCLUDES) 
NVCCFLAGS += -lpython${PYTHON_VERSION} 
NVCCFLAGS += -ltorch_python -ltorch_cuda -ltorch_cpu -ltorch -lc10_cuda -lc10
endif

# Architecture-specific flags
ifeq ($(GPU),B200)
NVCCFLAGS += -DKITTENS_HOPPER -DKITTENS_BLACKWELL -gencode arch=compute_100a,code=sm_100a
else ifeq ($(GPU),H100)
NVCCFLAGS += -DKITTENS_HOPPER -gencode arch=compute_90a,code=sm_90a
else
$(error Unsupported GPU: $(GPU). Please set GPU to B200 or H100.)
endif

all: $(OUT)

run: $(OUT)
	$(RUN_CMD)

ncu: $(OUT)
	ncu \
		--replay-mode kernel \
		--set full -f --export ./$(OUT).ncu-rep \
		$(RUN_CMD)

nsys: $(OUT)
	nsys profile \
		--stats=true \
		--trace cuda,osrt,nvtx,python-gil,syscall \
		--gpu-metrics-devices=all \
		--cuda-memory-usage true \
		--force-overwrite=true \
		-o ./$(OUT).nsys-rep \
		$(RUN_CMD)

$(OUT): $(SRC)
	$(NVCC) $(SRC) $(NVCCFLAGS) -o $(OUT)

ptx: $(SRC)
	$(NVCC) $(SRC) $(NVCCFLAGS) --ptx -o $(OUT).ptx

clean:
	rm -f $(OUT) $(OUT).ptx

.PHONY: all run bench clean
