ARCH := SM107

# Standalone mode
SRC := fp8_vr200_gemm.cu
OUT := fp8_vr200_gemm.out
CMD := ./fp8_vr200_gemm.out
CONFIG := standalone

# FP8 output mode
# SRC := fp8_vr200_gemm_fp8out.cu
# OUT := fp8_vr200_gemm_fp8out.out
# CMD := ./fp8_vr200_gemm_fp8out.out
# CONFIG := standalone

include ../../common.mk
