ARCH := SM107

# Standalone mode
SRC := nvfp4_vr200_gemm.cu
OUT := nvfp4_vr200_gemm.out
CMD := ./nvfp4_vr200_gemm.out
CONFIG := standalone

# FP4 output mode
# SRC := nvfp4_vr200_gemm_fp4out.cu
# OUT := nvfp4_vr200_gemm_fp4out.out
# CMD := ./nvfp4_vr200_gemm_fp4out.out
# CONFIG := standalone

include ../../common.mk
